### PR TITLE
MIR-1312 Display abstract in the current language of the application

### PR DESCRIPTION
**Pull request by Possommi**
[MIR-1312](https://mycore.atlassian.net/browse/MIR-1312)

[MIR-1312]: https://mycore.atlassian.net/browse/MIR-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rsteph-de** [comment]
I'v done the same thing for JSPDocportal: https://github.com/MyCoRe-Org/JSPDocportal/blob/fb5060cbd16abf02a01fe7a90e6f66705a699502/jspdocportal-ir-module/src/main/resources/xslt/docdetails/header_html.xsl#L191

**Comment by toKrause** [comment]
Functionally, this looks fine to me.

What I don't like is that this only works for the metadata page, not for search results (or the basket). So in a list of search results (or in the basket), users see the (beginning of) the “first” abstract, while on the details page they see the (presumably) “preferred” abstract.

Do you see an possibility to also select the “preferred” version in the other places?

**Comment by toKrause** [comment]
Okay, this is already partially covered by https://github.com/MyCoRe-Org/mir/pull/1006. Still, could you include the basket as well as part of either PR. I think the relevant code is here: https://github.com/MyCoRe-Org/mir/blob/85b6dab529e028ea28e23c6a5896bc7ccc7a1c9e/mir-module/src/main/resources/xsl/modsdetails-external.xsl#L913

**Review by toKrause — APPROVED** [review]

**Review by kkrebs — APPROVED** [review]

**Comment by Possommi** [comment]
Added documentation. See https://github.com/MyCoRe-Org/mycore-website/pull/60

**Comment by kkrebs** [comment]
looks good for me
https://www.mycore.de/documentation/apps/mir/migration/migrate_mir2024_06/

thx @Possommi

**Pull request merged**
