### PR TITLE
MIR-1042 exclude abstract from scopus import for license reasons

### PR DESCRIPTION
**Pull request by kkrebs**
[Link to jira](https://mycore.atlassian.net/browse/MIR-1042).

### CODE REVIEW

**Comment by fluetze** [comment]
Why did you remove
<xsl:template match="scopus:coredata/scopus:openaccess">
We need that.

In case the article is OA, the abstract is OA, too and could be preserved.

**Comment by kkrebs** [comment]
atm we have no OA classification yet in MIR. We could readd this later ... In scopus license they make no difference between non oa abstracts and oa abstracts. We have to sort this out, but for now we have the demand to remove abstract scopus import.

**Comment by fluetze** [comment]
Ok, I see that UBO has its own version of the file.

... but why not 
<xsl:apply-templates select="item/bibrecord/head/abstracts/abstract[current()/scopus:coredata/scopus:openaccess='1']" />
?

**Comment by kkrebs** [comment]
As discussed - we should ask scopus here. On there license page there is no difference between oa abstract and non oa abstract.

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
