### PR TITLE
merge 2020.06

### PR DESCRIPTION
**Pull request by kkrebs**

### CODE REVIEW

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 7140b6f4928550ddcd3bca48abd90e73bf0bce8c! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2922-pull_request-522

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with c5dcd0e5315603870ce7911c40756cc090c63bdd! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2937-pull_request-522

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with f5ff0a8db117aabb823e5c7e7b34082f219d1dda! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2941-pull_request-522

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 801306998393e8a05ae9dbb84470cc5999a48c48! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2945-pull_request-522

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/test/java/org/mycore/mir/migration/MIRMigration202006UtilsTest.java  1
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration202006Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=6120069&bid=20025726)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 947da0e542ba4489ba778699d4bf56b72c3682cd! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2947-pull_request-522

**Pull request merged**
