### PR TITLE
MIR-886 added dissemin sword implementation and stylesheets

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MIR-886).

### CODE REVIEW

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/sword2/MIRDisseminCollectionProvider.java  1
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  9
         

Clones added
============
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5154262&bid=16927650)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/sword2/MIRDisseminCollectionProvider.java  1
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  9
         

Clones added
============
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5154262&bid=16927650)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/sword2/MIRDisseminCollectionProvider.java  1
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  9
         

Clones added
============
- mir-module/src/main/java/org/mycore/mir/sword2/MIRMETSIngester.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5154262&bid=16927650)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with bd35de6635efcfe2cceb8f032eb2bea7427cfc0b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2543-pull_request-446

**Pull request merged**
