### PR TITLE
MIR-594 fix it

### PR DESCRIPTION
**Pull request by paschty**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 1925dbdab8d57e8604f0c374fb3fb023e05c056a! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/436-pull_request-77

**Comment by kkrebs** [comment]
this should be resolved with "MIR-591 Update to Selenium-Utils 0.6 and Selenium 3.3.1"

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with fabe3699f69154d692ba9709d57e57578b212a5b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/456-pull_request-77

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 88ffe5c54ba6b71bfbe56d4555bbae2048b5b720! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/458-pull_request-77

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 88ffe5c54ba6b71bfbe56d4555bbae2048b5b720! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/458-pull_request-77

**Pull request merged**
