### PR TITLE
MIR-904 some workflow for mir

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MIR-904).

### CODE REVIEW

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/MIRStateServlet.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5581457&bid=18295621)

**Comment by fluetze** [comment]
Why is read permission sufficient to change the document's state?

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/MIRStateServlet.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5581457&bid=18295621)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/MIRStateServlet.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5581457&bid=18295621)

**Pull request merged**
