### PR TITLE
MIR 1025 Option to enable mir_licences explicitly for mir_genres

### PR DESCRIPTION
**Pull request by golsch**
[Link to jira](https://mycore.atlassian.net/browse/MIR-1025).

### CODE REVIEW

**Review by kkrebs — CHANGES_REQUESTED** [review]
Works as designed, but please go back to the version with only one xsl:if statement. This isn't that complex and if you add some comment as documentation to this codeblock everything is fine.

**Comment by fluetze** [comment]
You could remove the <xsl:template match="@* | node()"> and simply include <xsl:include href="copynodes.xsl" />

**Review by fluetze — CHANGES_REQUESTED** [review]
You could remove the <xsl:template match="@* | node()"> and simply include <xsl:include href="copynodes.xsl" />

**Review by fluetze — CHANGES_REQUESTED** [review]
You could simplify the template match="items", just use
  <xsl:template match="items[string-length($genre) &gt; 0]" priority="1">
        <xsl:copy>
          <xsl:apply-templates select="@* | node()"/>
        </xsl:copy>
  </xsl:template>

**Comment by golsch** [comment]
> With use of <xsl:include href="copynodes.xsl" />
> you can even simpler remove the complete xsl:template match="items" without any functional change. It is useless.

I don't know how far the interpreter optimizes the code. The `items` template is meant as an optimization, so that the checks in `item` can be saved if no genre exists.

**Comment by fluetze** [comment]
> 
> 
> > With use of <xsl:include href="copynodes.xsl" />
> > you can even simpler remove the complete xsl:template match="items" without any functional change. It is useless.
> 
> I don't know how far the interpreter optimizes the code. The `items` template is meant as an optimization, so that the checks in `item` can be saved if no genre exists.

I understand, may be you can save some nanoseconds...

**Review by fluetze — APPROVED** [review]

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
