### PR TITLE
MIR-919 apply checkstyle and pmd rules

### PR DESCRIPTION
**Pull request by yagee-de**
no ticket only checkstyle fixes

### CODE REVIEW

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with e17802b85e0c5064135820883aa8d5899b415da1! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2715-pull_request-490

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 8a880753d9c9a4d6c8a04a7a77510abd0a745fe7! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2717-pull_request-490

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 16017928817960a0654d0ad643f32808b9758ef9! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2723-pull_request-490

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 6f3e256a6c027f51ff942d23bed0d59cdc6bc602! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2725-pull_request-490

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with d9f2d1ae5bfcdf905a48f3291479a2c6e537a4b5! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2727-pull_request-490

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201706Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration04Utils.java  3
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration201603Utils.java  5
- mir-module/src/main/java/org/mycore/mir/migration/MIRMigration03Utils.java  8
- mir-module/src/main/java/org/mycore/mir/impexp/MIRRelatedItemFinderUtils.java  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5779323&bid=18922478)

**Pull request merged**
