### PR TITLE
MIR-1285 Display realname rather than uid of user after login

### PR DESCRIPTION
**Pull request by Possommi**
[MIR-1285](https://mycore.atlassian.net/browse/MIR-1285).

[MIR-1285]: https://mycore.atlassian.net/browse/MIR-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by toKrause — APPROVED** [review]

**Review by toKrause — CHANGES_REQUESTED** [review]
This needs coordination with [MIR-1288](https://github.com/MyCoRe-Org/mir/pull/974)

This implementation uses the name, if available, in the UI. MIR-1288 still uses the user ID.

**Review by toKrause — APPROVED** [review]

**Comment by fluetze** [comment]
A user's real name is typically much wider than the user ID. So this change will affect the layout of MIR instances nad might be unwanted. Or is there any customization option?

**Comment by toKrause** [comment]
Since this is a behavior change that targets the LTS branch, the change should technically
be optional, i.e. configurable. But this specific change is so undramatic that I wouldn't insist on that.

**Comment by Possommi** [comment]
I am with @toKrause on the matter.

From user perspective its more friendly to read the name rather than the uid. In particular when a user is signed in via SSO where the username could be anything (uid, scroped attribute or even some sort of uuid).

**Comment by Possommi** [comment]
I will introduce a new property making the behaviour configurable

**Comment by Possommi** [comment]
> A user's real name is typically much wider than the user ID. So this change will affect the layout of MIR instances nad might be unwanted. Or is there any customization option?

@fluetze I added a property and the default behaviour remains unchanged

**Pull request merged**
