### PR TITLE
MIR-842 fix layout issues caused by bootsrap 4 migration

### PR DESCRIPTION
**Pull request by TiloNN**
Replaced outdated bs3 classes in mir too.

[Link to jira](https://mycore.atlassian.net/browse/MIR-842).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with af4ba64769791c127a16a21fa071094f9bdee848! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2208-pull_request-393

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with af4ba64769791c127a16a21fa071094f9bdee848! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2208-pull_request-393

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 353a5fc2d04507d2a80ce4b7dc991ecf7d3947c8! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2210-pull_request-393

**Comment by kkrebs** [comment]
tests depends on https://github.com/MyCoRe-Org/mycore/pull/842

**Pull request merged**
