### PR TITLE
MCR-2270 use mods implementation of mycore-csl

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2270).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 17a9861296994e3f7f5e1d9d601bbfbe012bbb5b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2909-pull_request-521

**Review by kkrebs — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 17a9861296994e3f7f5e1d9d601bbfbe012bbb5b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2909-pull_request-521

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 17a9861296994e3f7f5e1d9d601bbfbe012bbb5b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2909-pull_request-521

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 17a9861296994e3f7f5e1d9d601bbfbe012bbb5b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2909-pull_request-521

**Pull request merged**
