### PR TITLE
MIR-961-search_entity_does_not_associate_identifier

### PR DESCRIPTION
**Pull request by rochpaul**
Adapt mir:role.repeated template and generalize queries in
search-entity.js

[Link to jira](https://mycore.atlassian.net/browse/MIR-961).

### CODE REVIEW

**Comment by toKrause** [comment]
I've look at the changes and incorporated them into my application. A first search work as expected, but all subsequent searches have the same problem as before. If I'm correct, It's necessary and sufficient to remove the explicit `select`-element name in line [777](https://github.com/MyCoRe-Org/mir/blob/b555ab904015d55d32955638dbe1e9b07da295c9/mir-module/src/main/resources/META-INF/resources/js/jquery.search-entity.js#L777) as well, i.e. change it to:

```
nameIdTypesElements = $(itemPersonExtendedBox).find('[name*="/mods:nameIdentifier"]');
```
But I still haven't exactly understood whats happening in the `updateOutput`-method, so please take this with a grain of salt and test for yourself.

**Comment by rochpaul** [comment]
Hello Thorsten,
thank you for your review and the advice.
I have checked the described behavior and I can confirm it. 
With another search (the error does not appear if you change the identifier type) the underlying id of selected search entity will be ignored.
There is thrown an exception on renewed selection in js console:
`
jquery.search-entity.js:821 Uncaught TypeError: Cannot read property 'name' of undefined
    at a.updateOutput (jquery.search-entity.js:821)
    at HTMLAnchorElement.<anonymous> (jquery.search-entity.js:709)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
`

I will fix this as soon as possible.
Best regards,
Paul

**Comment by rochpaul** [comment]
Hi Thorsten,
the issue should be fixed.
Please can you verify and confirm?

Best regards,
Paul

**Review by kkrebs — APPROVED** [review]
🚢

**Pull request merged**
