### PR TITLE
MIR-151 Integration tests with SOLR 7

### PR DESCRIPTION
**Pull request by paschty**
# DO NOT MERGE YET.
[MIR-151 Integration tests with SOLR 7](https://mycore.atlassian.net/browse/MIR-151)

## Changes
- removed solr.war from cargo because there is no official .war
- added solr-runner plugin which:
  - downloads a specific solr
  - copies solr-config to mycore-home
  - starts and stops solr
- start/stop solr before/after integration test
- cleaned the schema.xml
  - i used a "fresh" solr configuration
  - copied all the mycore-stuff to it
  - removed most of the default stuff which we dont use in mycore

## TODO
- Maybe find a better location for solr config files (@yagee-de please comment)
- Maybe let mir-wizard copy/download the new configuration, because currently it downloads the 4.* config (@adlerre please comment)

## How to test this
- check out the right branch
- run `mvn clean install -Djetty` to run the integration tests (should work out of the Box) 
- change the url in the mycore.properties to match the new port `8983` (which is the solr standard port)  
- run `mvn solr-runner:copyHome solr-runner:start` in mir-webapp folder to copy all solr cofiguration files and start solr in the background.

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with aa5c8528c4e04884aa22091d5ff0747fff95727e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1073-pull_request-187

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with e47f69ebc5c9da492d574b9e27058aa58d8f5d6e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1085-pull_request-187

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 72e281fd7e64d9d176e7a919e5e8ea18cf6475c3! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1130-pull_request-187

**Comment by yagee-de** [comment]
Error when starting solr:

>
> Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/yagee-de/.mycore/dev-mir/data/solr/data/index/segments_p86"))): 3 (needs to be between 6 and 7). This version of Lucene only supports indexes created with release 6.0 and later.

**Comment by yagee-de** [comment]
Error while indexing:

> Error while submitting index handler. java.util.concurrent.CompletionException: java.lang.RuntimeException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/mir: java.io.FileNotFoundException: /Users/yagee-de/.mycore/dev-mir/data/solr/conf/tikaconfig.xml (No such file or directory)

**Comment by paschty** [comment]
see 28ae122 ..

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with f3f207b2a88edbbb4f08fdf8b5d1b54cebcb967a! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1137-pull_request-187

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with f3f207b2a88edbbb4f08fdf8b5d1b54cebcb967a! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1137-pull_request-187

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 2398657724e714f5e6f7cd8b6d40ed08fd4e73de! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1141-pull_request-187

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 16c40d8b4583da4fa62b7ebd16ac5f3d5ade1344! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/1158-pull_request-187

**Pull request merged**
