### PR TITLE
MIR-638 use mycore-csl for citations

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MIR-638).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 3ede1154bfd37e67a3e08e08acb151ed2deda49e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2554-pull_request-465

**Comment by sebhofmann** [comment]
Requires https://github.com/MyCoRe-Org/mycore/pull/953

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 3ede1154bfd37e67a3e08e08acb151ed2deda49e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2554-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 3ede1154bfd37e67a3e08e08acb151ed2deda49e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2554-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 3ede1154bfd37e67a3e08e08acb151ed2deda49e! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2554-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 941f16dd6767c3db8dcba368527f58771bf1101a! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2570-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 62d22545067a0cea9114d0ad372dfe64b28ad893! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2572-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 62d22545067a0cea9114d0ad372dfe64b28ad893! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2572-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with d7220714589ce82b32f69b4dd0f5d6d8bbcf5c33! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2574-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 4869bab748856aeec73076bb75349a4f4d53ca7a! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2584-pull_request-465

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with c8174535a5fa1258b5bed0580a22a4dba6cfea3c! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2586-pull_request-465

**Pull request merged**
