### PR TITLE
MCR-1874 replace calls to MCRConfiguration

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1874).

### CODE REVIEW

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ mir-module/src/main/java/org/mycore/mir/authorization/ReCaptcha.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5301042&bid=17351186)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 63abce280b4294d3cbb6711f0461def53282d70b! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/2529-pull_request-458

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ mir-module/src/main/java/org/mycore/mir/authorization/ReCaptcha.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5301042&bid=17351186)

**Comment by yagee-de** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ mir-module/src/main/java/org/mycore/mir/authorization/ReCaptcha.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mir/pullRequest?prid=5301042&bid=17351186)

**Pull request merged**
