### PR TITLE
MIR-1258 Set left attribute in .hit_icon_overlay to 16px

### PR DESCRIPTION
**Pull request by Possommi**
[Link to jira](https://mycore.atlassian.net/browse/MIR-1258).

### CODE REVIEW

**Review by toKrause — CHANGES_REQUESTED** [review]
In my repository (which uses slightly larger icons then standard MIR):

Currently (definitely broken):
image

With proposed changes (still not correct):
image

Should be dynamically centered via CSS, for example with:
```
  left: 0;
  right: 0;
  margin-left: auto;
  margin-right: auto;
```
image

Or, preferably, taking the visual imbalance of the icons into account:
```
  left: -8%;
  right: 0;
  margin-left: auto;
  margin-right: auto;
```
image

Appears to be working for different sizes: 
image

**Comment by sebhofmann** [comment]
I think the current position of the arrow is intentional.

**Comment by toKrause** [comment]
> I think the current position of the arrow is intentional.

very weird, if this is intentional

image

**Comment by sebhofmann** [comment]
I think it looks weird too, i tried to fix it, when i migrated the icons to IIIF, but i was told the arrow should line up with the border and it is intentional. 
Bildschirmfoto 2023-11-20 um 15 31 03

**Comment by Possommi** [comment]
> that looks ridiculous, imho

I am quite new to MIR and to be honest when I first saw it I thought that the layout must be broken.

**Pull request closed without merging**
