### PR TITLE
MIR-847 classifications are not indexed after installation

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MIR-847).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 579d2a3e6f59fe309653879376066327814f43c3! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/3169-pull_request-567

**Review by kkrebs — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 579d2a3e6f59fe309653879376066327814f43c3! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/3169-pull_request-567

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 579d2a3e6f59fe309653879376066327814f43c3! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/3169-pull_request-567

**Comment by MyCoRe-Travis** [comment]
Something gone wrong with 579d2a3e6f59fe309653879376066327814f43c3! 
 Please Check https://github.com/MyCoRe-Travis/MIR_test_artifacts/tree/3169-pull_request-567

**Pull request merged**
